name: e_shop
description: "A new Flutter project."


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'


# ****************** Packages ******************


dependencies:
  flutter:
    sdk: flutter


  # Utility Packages 
  
  cupertino_icons: ^1.0.6
  iconsax: ^0.0.8
  google_fonts: ^6.2.1
  http: ^1.2.2
  intl: ^0.19.0
  logger: ^2.4.0
  url_launcher: ^6.3.0
  get: ^4.6.6
  get_storage: ^2.1.1
  flutter_native_splash: ^2.4.1
  smooth_page_indicator: ^1.2.0+3
  
  
  
  

  # State Management
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6

  # Product Specific

 # ****************** Packages End Here ******************

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  
  flutter_lints: ^3.0.0


flutter:

  uses-material-design: true

 # ****************** Local Assets ******************

  assets:
    - assets/Icons/
    - assets/images/
    - assets/images/on_boarding_images/
    - assets/logo/

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
