// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkdNrPheeMDA6I_xBqNwRXp0Ljb0eECGs',
    appId: '1:161713497072:web:a378e152c22b523678b335',
    messagingSenderId: '161713497072',
    projectId: 'fir-authentication-37ad0',
    authDomain: 'fir-authentication-37ad0.firebaseapp.com',
    storageBucket: 'fir-authentication-37ad0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVOcUWsckFv6qnJZqR-kLmdiJKYKZ1a38',
    appId: '1:161713497072:android:f0cd725b8b84652f78b335',
    messagingSenderId: '161713497072',
    projectId: 'fir-authentication-37ad0',
    storageBucket: 'fir-authentication-37ad0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzARd_W2CyF5qXwidFyGD_uA8fMxxwb8k',
    appId: '1:161713497072:ios:28bcaf24251f0c8e78b335',
    messagingSenderId: '161713497072',
    projectId: 'fir-authentication-37ad0',
    storageBucket: 'fir-authentication-37ad0.appspot.com',
    iosBundleId: 'com.example.firebaseAuthentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzARd_W2CyF5qXwidFyGD_uA8fMxxwb8k',
    appId: '1:161713497072:ios:28bcaf24251f0c8e78b335',
    messagingSenderId: '161713497072',
    projectId: 'fir-authentication-37ad0',
    storageBucket: 'fir-authentication-37ad0.appspot.com',
    iosBundleId: 'com.example.firebaseAuthentication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkdNrPheeMDA6I_xBqNwRXp0Ljb0eECGs',
    appId: '1:161713497072:web:ec0090c59def733878b335',
    messagingSenderId: '161713497072',
    projectId: 'fir-authentication-37ad0',
    authDomain: 'fir-authentication-37ad0.firebaseapp.com',
    storageBucket: 'fir-authentication-37ad0.appspot.com',
  );
}
